apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: harbor-cluster-operator-controller-manager-metrics-service
  namespace: harbor-cluster-operator-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: harbor-cluster-operator-controller-manager
  namespace: harbor-cluster-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        #image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
        image: {{ .Values.manager.proxy.image }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        #- --metrics-addr=127.0.0.1:8080
        - "--metrics-addr={{ .Values.manager.metrics.addr }}:{{ .Values.manager.metrics.port }}"
        - --enable-leader-election
        command:
        - /manager
        image: {{ .Values.manager.manager.image }}
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          {{- toYaml .Values.manager.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
