apiVersion: v1
kind: Service
metadata:
  name: harbor-cluster-operator-webhook-service
  namespace: harbor-cluster-operator-system
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: harbor-cluster-operator-system/harbor-cluster-operator-serving-cert
  creationTimestamp: null
  name: harbor-cluster-operator-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: harbor-cluster-operator-webhook-service
      namespace: harbor-cluster-operator-system
      path: /validate-goharbor-io-v1-harborcluster
  failurePolicy: Fail
  name: vharborcluster.kb.io
  rules:
  - apiGroups:
    - goharbor.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - harborclusters
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: harbor-cluster-operator-system/harbor-cluster-operator-serving-cert
  creationTimestamp: null
  name: harbor-cluster-operator-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: harbor-cluster-operator-webhook-service
      namespace: harbor-cluster-operator-system
      path: /mutate-goharbor-io-v1-harborcluster
  failurePolicy: Fail
  name: mharborcluster.kb.io
  rules:
  - apiGroups:
    - goharbor.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - harborclusters
